image: alpine:latest

before_script: |
  apk update
  apk add npm

pages:
  stage: deploy
  script: |
    mkdir -p ./public
    cd ./docusaurus-static
    npm install
    npm run build+postprocess
    mv ./build ../public/docusaurus-static
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

